update to read the newly reported infos as well and better parser

diff --git a/debian/mksh-status b/debian/mksh-status
--- a/debian/mksh-status
+++ b/debian/mksh-status
@@ -95,48 +95,72 @@ EOF
 
 i=-1
 while (( ++i < narchs )); do
-	if [[ -n ${logs[i]} ]]; then (
-		llc=$(sed --posix -n \
-		    '/^D:loglibc:final(\([^)]*\)) \(.*\) finishing$/{s//\1)\2/p;q;}' \
-		    <arch."${archs[i]}" | sed --posix \
-		    -e 'y/()/{}/' -e 's/}/)/' \
-		    -e 's/_{[^} ]*}//g' \
-		    -e "s/'/'\\\\''/g" -e 's/=\([^ ]*\)/='\''\1'\''/g')
-		vsn=${llc%%')'*}
-		eval "$(sed --posix \
-		    -e 's/_(\([0-9]*\)_\([^) ]\)[^) ]*)\([a-z]\)/\3\/\1\2/g' \
-		    -e 's/RTCHK/rtchk/g' -e 's/MTEST/mtest/g' \
-		    -e 's/testsuite-failed/fail/g' \
-		    -e 's/passed-but-notty/ntty/g' \
-		    -e 's/succeeded-tested/succ/g' \
-		    <<-EOF
-			${llc#*')'}
-		EOF
-		)"
-		case $vsn:${states[i]} {
-		(:Build-Attempted|:Failed)
-			vsn=$(sed --posix -n \
-			    '/^Version: /{s///p;q;}' \
-			    <arch."${archs[i]}")
-			if [[ -n $vsn ]]; then
-				vsn=⸘$vsn
-			else
-				vsn='(¿?'
-			fi
-			mksh_glibc=⸘${states[i]}${mksh_glibc:+ $mksh_glibc}
-			;;
-		(*)
-			vsn='('${vsn:-¿?}
-		}
-		cat >>columnus <<-EOF
-			${archs[i]})mksh)${system:-⁉ unset})${mksh_klibc:-⁉ unset})${mksh_musl:-⁉ unset})${mksh_dietlibc:-⁉ unset})${mksh_glibc:-⁉ unset}
-			 )lksh) ↑ version$vsn)${lksh_klibc:-⁉ unset})${lksh_musl:-⁉ unset})${lksh_dietlibc:-⁉ unset})${lksh_glibc:-⁉ unset}
-		EOF
-	); else
+	if [[ -z ${logs[i]} ]]; then
 		cat >>columnus <<-EOF
 			${archs[i]})-)⁉ missing)⁉ missing)⁉ missing)⁉ missing)⁉ absent
 		EOF
+		continue
 	fi
+	fn=arch.${archs[i]}
+
+	llc=$(sed --posix -n \
+	    -e '/^D:loglibc:start(\([^)]*\)) \(.*\) initialising$/s//vs=v\1 \2/p' \
+	    -e '/^D:loglibc:final(\([^)]*\)) \(.*\) finishing$/s//vt=v\1 \2/p' \
+	    "$fn" | sed --posix 's/ \([a-z][a-z0-9_]*=\)/\nvv\1/g' | sed --posix \
+	    -e 's!_(\([0-9]*\)_unexpected)f!f/\1u!' \
+	    -e 's/RTCHK/rtchk/g' -e 's/MTEST/mtest/g' \
+	    -e 's/testsuite-failed/fail/g' \
+	    -e 's/passed-but-notty/ntty/g' \
+	    -e 's/succeeded-tested/succ/g' \
+	    -e 's/_([^) ]*)//' \
+	    -e "s/'/'\\\\''/g" -e 's/=\(.*\)$/='\''\1'\''/')
+	case $nl$llc in (*"${nl}vs="*"${nl}vs="*)
+		echo >&2 "W: multiple loglibc:start lines; log is fishy: $fn" ;;
+	esac
+	case $nl$llc in (*"${nl}vt="*"${nl}vt="*)
+		echo >&2 "W: multiple loglibc:final lines; log is fishy: $fn" ;;
+	esac
+	vs= vt= vvarch= vvbred= vvsystem=
+	vvmksh_klibc= vvmksh_musl= vvmksh_dietlibc= vvmksh_glibc=
+	vvlksh_klibc= vvlksh_musl= vvlksh_dietlibc= vvlksh_glibc=
+	eval "$llc"
+	if test -z "$vs"; then
+		vs=$vt vvarch= vvbred=
+	fi
+	if test -z "$vt"; then
+		vt=$vs vvsystem=
+		vvmksh_klibc= vvmksh_musl= vvmksh_dietlibc= vvmksh_glibc=
+		vvlksh_klibc= vvlksh_musl= vvlksh_dietlibc= vvlksh_glibc=
+	fi
+	case x$vvbred in
+	x|x0)
+		bred=↑
+		;;
+	x1)
+		bred=⇑
+		;;
+	*)
+		echo >&2 "W: invalid bred ($vvbred); log is fishy: $fn"
+		bred=⇓
+		;;
+	esac
+	test x"$vs" = x"$vt" || echo >&2 "W: version difference" \
+	    "($vs) vs. ($vt); log is fishy: $fn"
+	vsn=${vs#v}
+
+	case $vsn:${states[i]} {
+	(:Build-Attempted|:Failed)
+		vsn=$(sed --posix -n '/^Version: /{s///p;q;}' <"$fn")
+		vsn=⸘${vsn:-'¿?'}
+		vvmksh_glibc=⸘${states[i]}${vvmksh_glibc:+ $vvmksh_glibc}
+		;;
+	(*)
+		vsn='('${vsn:-¿?}
+	}
+	cat >>columnus <<-EOF
+		${archs[i]})mksh)${vvsystem:-⁉ unset})${vvmksh_klibc:-⁉ unset})${vvmksh_musl:-⁉ unset})${vvmksh_dietlibc:-⁉ unset})${vvmksh_glibc:-⁉ unset}
+		${vvarch:- })lksh) $bred version$vsn)${vvlksh_klibc:-⁉ unset})${vvlksh_musl:-⁉ unset})${vvlksh_dietlibc:-⁉ unset})${vvlksh_glibc:-⁉ unset}
+	EOF
 done
 
 column -ts')' <columnus >tabularis
@@ -149,18 +173,22 @@ ed -s tabularis <<-\EOF
 	,g/✗[^ ]*/s//[0;31;40m&/g
 	,g/☒[^ ]*/s//[0;1;35;40m&/g
 	,g/✔[^ ]*/s//[0;1;32;40m&/g
-	,g/\( ↑[^(]*\)(\([^ ]*\) /s//[0;1;30;40m\1 [0;1m\2 /
-	,g/\( ↑.*\)⸘\([^ ]*\) /s//[0;36;40m\1 [1m\2 /
-	,g/¿?/s//[31m&/g
+	,g/ ↑\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;1m\2 /
+	,g/ ↑\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [1m\2 /
+	,g/ ⇑\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;31;1m\2 /
+	,g/ ⇑\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [31;1m\2 /
+	,g/ ⇓\([^(]*\)(\([^ ]*\) /s//[0;1;30;40m ↑\1 [0;5;1m\2 /
+	,g/ ⇓\(.*\)⸘\([^ ]*\) /s//[0;36;40m ↑\1 [5;1m\2 /
 	,g/⸘/s//[0;1;36;40m/g
 	1s/^/[0m/
 	1s/  */&| /g
 	1s/$/   /
-	2,$s/^[^ ]/[0;1;34;40m&/
-	2,$s/  */[0m&| /g
+	2,$g/^[^ ]/s//[0;1;34;40m&/
+	2,$g/  */s//[0m&| /g
 	,g/ |/s//|/g
 	1t$
 	2,$g/^[^m]*m[^ ]/.-1s/.0/&;4/g
+	,g/^/s//[0;4m/
 	,g/$/s//[0m/
 	w
 	q
